"""empty message

Revision ID: 7fcb5ad499e6
Revises: e7a98131d551
Create Date: 2023-06-11 00:16:05.497102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcb5ad499e6'
down_revision = 'e7a98131d551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reset_password_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reset_password_token_token'), ['token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_password_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reset_password_token_token'))

    op.drop_table('reset_password_token')
    # ### end Alembic commands ###
